"""update application and report models

Revision ID: 2faba9cf9fe4
Revises: 66234075237a
Create Date: 2026-03-18 20:04:46.484859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2faba9cf9fe4'
down_revision: Union[str, Sequence[str], None] = '66234075237a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application', 'message')
    # ### end Alembic commands ###
