"""add_timestamps_to_report

Revision ID: 429392f1745b
Revises: 51aaf28435f2
Create Date: 2026-03-19 19:49:38.771510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '429392f1745b'
down_revision: Union[str, Sequence[str], None] = '51aaf28435f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('report', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_report_created_at'), 'report', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_created_at'), table_name='report')
    op.drop_column('report', 'updated_at')
    op.drop_column('report', 'created_at')
    # ### end Alembic commands ###
