"""update_report_model

Revision ID: baf78d7a6b6e
Revises: 2faba9cf9fe4
Create Date: 2026-03-18 20:27:04.247553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baf78d7a6b6e'
down_revision: Union[str, Sequence[str], None] = '2faba9cf9fe4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('report_type', sa.String(), nullable=True))
    op.add_column('report', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report', 'image_url')
    op.drop_column('report', 'report_type')
    # ### end Alembic commands ###
