"""add user profile fields

Revision ID: cc12c5e5713b
Revises: baf78d7a6b6e
Create Date: 2026-03-18 21:13:35.733565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc12c5e5713b'
down_revision: Union[str, Sequence[str], None] = 'baf78d7a6b6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('user', sa.Column('avatar', sa.String(), nullable=True))
    op.add_column('user', sa.Column('bio', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'bio')
    op.drop_column('user', 'avatar')
    op.drop_column('user', 'gender')
    op.drop_column('user', 'age')
    # ### end Alembic commands ###
