"""Add details to pet model

Revision ID: cfa24d691477
Revises: 25b72f8e7364
Create Date: 2026-03-19 17:44:23.247955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfa24d691477'
down_revision: Union[str, Sequence[str], None] = '25b72f8e7364'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pet', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('pet', sa.Column('size', sa.String(), nullable=True))
    op.add_column('pet', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pet', 'image_url')
    op.drop_column('pet', 'size')
    op.drop_column('pet', 'gender')
    # ### end Alembic commands ###
